//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.CustomersServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Musteri_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Musteri_AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Musteri_SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Musteri_TCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Musteri_KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Musteri_SifreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Musteri_ID {
            get {
                return this.Musteri_IDField;
            }
            set {
                if ((this.Musteri_IDField.Equals(value) != true)) {
                    this.Musteri_IDField = value;
                    this.RaisePropertyChanged("Musteri_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Musteri_Ad {
            get {
                return this.Musteri_AdField;
            }
            set {
                if ((object.ReferenceEquals(this.Musteri_AdField, value) != true)) {
                    this.Musteri_AdField = value;
                    this.RaisePropertyChanged("Musteri_Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Musteri_Soyad {
            get {
                return this.Musteri_SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.Musteri_SoyadField, value) != true)) {
                    this.Musteri_SoyadField = value;
                    this.RaisePropertyChanged("Musteri_Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Musteri_TC {
            get {
                return this.Musteri_TCField;
            }
            set {
                if ((object.ReferenceEquals(this.Musteri_TCField, value) != true)) {
                    this.Musteri_TCField = value;
                    this.RaisePropertyChanged("Musteri_TC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Musteri_KullaniciAdi {
            get {
                return this.Musteri_KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Musteri_KullaniciAdiField, value) != true)) {
                    this.Musteri_KullaniciAdiField = value;
                    this.RaisePropertyChanged("Musteri_KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Musteri_Sifre {
            get {
                return this.Musteri_SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.Musteri_SifreField, value) != true)) {
                    this.Musteri_SifreField = value;
                    this.RaisePropertyChanged("Musteri_Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomersServices.ConvertSoap")]
    public interface ConvertSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki CustomerFindResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerFind", ReplyAction="*")]
        WindowsFormsApp1.CustomersServices.CustomerFindResponse CustomerFind(WindowsFormsApp1.CustomersServices.CustomerFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerFind", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.CustomerFindResponse> CustomerFindAsync(WindowsFormsApp1.CustomersServices.CustomerFindRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki entity öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomer", ReplyAction="*")]
        WindowsFormsApp1.CustomersServices.InsertCustomerResponse InsertCustomer(WindowsFormsApp1.CustomersServices.InsertCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.InsertCustomerResponse> InsertCustomerAsync(WindowsFormsApp1.CustomersServices.InsertCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        bool DeleteCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int id);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetCustomerResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomer", ReplyAction="*")]
        WindowsFormsApp1.CustomersServices.GetCustomerResponse GetCustomer(WindowsFormsApp1.CustomersServices.GetCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.GetCustomerResponse> GetCustomerAsync(WindowsFormsApp1.CustomersServices.GetCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Updates", ReplyAction="*")]
        bool Updates(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Updates", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdatesAsync(int id);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki userName öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginCheck", ReplyAction="*")]
        WindowsFormsApp1.CustomersServices.LoginCheckResponse LoginCheck(WindowsFormsApp1.CustomersServices.LoginCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.LoginCheckResponse> LoginCheckAsync(WindowsFormsApp1.CustomersServices.LoginCheckRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerFindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerFind", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.CustomersServices.CustomerFindRequestBody Body;
        
        public CustomerFindRequest() {
        }
        
        public CustomerFindRequest(WindowsFormsApp1.CustomersServices.CustomerFindRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerFindRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        public CustomerFindRequestBody() {
        }
        
        public CustomerFindRequestBody(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerFindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerFindResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.CustomersServices.CustomerFindResponseBody Body;
        
        public CustomerFindResponse() {
        }
        
        public CustomerFindResponse(WindowsFormsApp1.CustomersServices.CustomerFindResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerFindResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.CustomersServices.Customers CustomerFindResult;
        
        public CustomerFindResponseBody() {
        }
        
        public CustomerFindResponseBody(WindowsFormsApp1.CustomersServices.Customers CustomerFindResult) {
            this.CustomerFindResult = CustomerFindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCustomer", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.CustomersServices.InsertCustomerRequestBody Body;
        
        public InsertCustomerRequest() {
        }
        
        public InsertCustomerRequest(WindowsFormsApp1.CustomersServices.InsertCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.CustomersServices.Customers entity;
        
        public InsertCustomerRequestBody() {
        }
        
        public InsertCustomerRequestBody(WindowsFormsApp1.CustomersServices.Customers entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.CustomersServices.InsertCustomerResponseBody Body;
        
        public InsertCustomerResponse() {
        }
        
        public InsertCustomerResponse(WindowsFormsApp1.CustomersServices.InsertCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertCustomerResult;
        
        public InsertCustomerResponseBody() {
        }
        
        public InsertCustomerResponseBody(bool InsertCustomerResult) {
            this.InsertCustomerResult = InsertCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomer", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.CustomersServices.GetCustomerRequestBody Body;
        
        public GetCustomerRequest() {
        }
        
        public GetCustomerRequest(WindowsFormsApp1.CustomersServices.GetCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCustomerRequestBody {
        
        public GetCustomerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.CustomersServices.GetCustomerResponseBody Body;
        
        public GetCustomerResponse() {
        }
        
        public GetCustomerResponse(WindowsFormsApp1.CustomersServices.GetCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.CustomersServices.Customers[] GetCustomerResult;
        
        public GetCustomerResponseBody() {
        }
        
        public GetCustomerResponseBody(WindowsFormsApp1.CustomersServices.Customers[] GetCustomerResult) {
            this.GetCustomerResult = GetCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginCheck", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.CustomersServices.LoginCheckRequestBody Body;
        
        public LoginCheckRequest() {
        }
        
        public LoginCheckRequest(WindowsFormsApp1.CustomersServices.LoginCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPass;
        
        public LoginCheckRequestBody() {
        }
        
        public LoginCheckRequestBody(string userName, string userPass) {
            this.userName = userName;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginCheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.CustomersServices.LoginCheckResponseBody Body;
        
        public LoginCheckResponse() {
        }
        
        public LoginCheckResponse(WindowsFormsApp1.CustomersServices.LoginCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginCheckResult;
        
        public LoginCheckResponseBody() {
        }
        
        public LoginCheckResponseBody(bool LoginCheckResult) {
            this.LoginCheckResult = LoginCheckResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConvertSoapChannel : WindowsFormsApp1.CustomersServices.ConvertSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.CustomersServices.ConvertSoap>, WindowsFormsApp1.CustomersServices.ConvertSoap {
        
        public ConvertSoapClient() {
        }
        
        public ConvertSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.CustomersServices.CustomerFindResponse WindowsFormsApp1.CustomersServices.ConvertSoap.CustomerFind(WindowsFormsApp1.CustomersServices.CustomerFindRequest request) {
            return base.Channel.CustomerFind(request);
        }
        
        public WindowsFormsApp1.CustomersServices.Customers CustomerFind(int ID) {
            WindowsFormsApp1.CustomersServices.CustomerFindRequest inValue = new WindowsFormsApp1.CustomersServices.CustomerFindRequest();
            inValue.Body = new WindowsFormsApp1.CustomersServices.CustomerFindRequestBody();
            inValue.Body.ID = ID;
            WindowsFormsApp1.CustomersServices.CustomerFindResponse retVal = ((WindowsFormsApp1.CustomersServices.ConvertSoap)(this)).CustomerFind(inValue);
            return retVal.Body.CustomerFindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.CustomerFindResponse> WindowsFormsApp1.CustomersServices.ConvertSoap.CustomerFindAsync(WindowsFormsApp1.CustomersServices.CustomerFindRequest request) {
            return base.Channel.CustomerFindAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.CustomerFindResponse> CustomerFindAsync(int ID) {
            WindowsFormsApp1.CustomersServices.CustomerFindRequest inValue = new WindowsFormsApp1.CustomersServices.CustomerFindRequest();
            inValue.Body = new WindowsFormsApp1.CustomersServices.CustomerFindRequestBody();
            inValue.Body.ID = ID;
            return ((WindowsFormsApp1.CustomersServices.ConvertSoap)(this)).CustomerFindAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.CustomersServices.InsertCustomerResponse WindowsFormsApp1.CustomersServices.ConvertSoap.InsertCustomer(WindowsFormsApp1.CustomersServices.InsertCustomerRequest request) {
            return base.Channel.InsertCustomer(request);
        }
        
        public bool InsertCustomer(WindowsFormsApp1.CustomersServices.Customers entity) {
            WindowsFormsApp1.CustomersServices.InsertCustomerRequest inValue = new WindowsFormsApp1.CustomersServices.InsertCustomerRequest();
            inValue.Body = new WindowsFormsApp1.CustomersServices.InsertCustomerRequestBody();
            inValue.Body.entity = entity;
            WindowsFormsApp1.CustomersServices.InsertCustomerResponse retVal = ((WindowsFormsApp1.CustomersServices.ConvertSoap)(this)).InsertCustomer(inValue);
            return retVal.Body.InsertCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.InsertCustomerResponse> WindowsFormsApp1.CustomersServices.ConvertSoap.InsertCustomerAsync(WindowsFormsApp1.CustomersServices.InsertCustomerRequest request) {
            return base.Channel.InsertCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.InsertCustomerResponse> InsertCustomerAsync(WindowsFormsApp1.CustomersServices.Customers entity) {
            WindowsFormsApp1.CustomersServices.InsertCustomerRequest inValue = new WindowsFormsApp1.CustomersServices.InsertCustomerRequest();
            inValue.Body = new WindowsFormsApp1.CustomersServices.InsertCustomerRequestBody();
            inValue.Body.entity = entity;
            return ((WindowsFormsApp1.CustomersServices.ConvertSoap)(this)).InsertCustomerAsync(inValue);
        }
        
        public bool DeleteCustomer(int id) {
            return base.Channel.DeleteCustomer(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int id) {
            return base.Channel.DeleteCustomerAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.CustomersServices.GetCustomerResponse WindowsFormsApp1.CustomersServices.ConvertSoap.GetCustomer(WindowsFormsApp1.CustomersServices.GetCustomerRequest request) {
            return base.Channel.GetCustomer(request);
        }
        
        public WindowsFormsApp1.CustomersServices.Customers[] GetCustomer() {
            WindowsFormsApp1.CustomersServices.GetCustomerRequest inValue = new WindowsFormsApp1.CustomersServices.GetCustomerRequest();
            inValue.Body = new WindowsFormsApp1.CustomersServices.GetCustomerRequestBody();
            WindowsFormsApp1.CustomersServices.GetCustomerResponse retVal = ((WindowsFormsApp1.CustomersServices.ConvertSoap)(this)).GetCustomer(inValue);
            return retVal.Body.GetCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.GetCustomerResponse> WindowsFormsApp1.CustomersServices.ConvertSoap.GetCustomerAsync(WindowsFormsApp1.CustomersServices.GetCustomerRequest request) {
            return base.Channel.GetCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.GetCustomerResponse> GetCustomerAsync() {
            WindowsFormsApp1.CustomersServices.GetCustomerRequest inValue = new WindowsFormsApp1.CustomersServices.GetCustomerRequest();
            inValue.Body = new WindowsFormsApp1.CustomersServices.GetCustomerRequestBody();
            return ((WindowsFormsApp1.CustomersServices.ConvertSoap)(this)).GetCustomerAsync(inValue);
        }
        
        public bool Updates(int id) {
            return base.Channel.Updates(id);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatesAsync(int id) {
            return base.Channel.UpdatesAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.CustomersServices.LoginCheckResponse WindowsFormsApp1.CustomersServices.ConvertSoap.LoginCheck(WindowsFormsApp1.CustomersServices.LoginCheckRequest request) {
            return base.Channel.LoginCheck(request);
        }
        
        public bool LoginCheck(string userName, string userPass) {
            WindowsFormsApp1.CustomersServices.LoginCheckRequest inValue = new WindowsFormsApp1.CustomersServices.LoginCheckRequest();
            inValue.Body = new WindowsFormsApp1.CustomersServices.LoginCheckRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            WindowsFormsApp1.CustomersServices.LoginCheckResponse retVal = ((WindowsFormsApp1.CustomersServices.ConvertSoap)(this)).LoginCheck(inValue);
            return retVal.Body.LoginCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.LoginCheckResponse> WindowsFormsApp1.CustomersServices.ConvertSoap.LoginCheckAsync(WindowsFormsApp1.CustomersServices.LoginCheckRequest request) {
            return base.Channel.LoginCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.CustomersServices.LoginCheckResponse> LoginCheckAsync(string userName, string userPass) {
            WindowsFormsApp1.CustomersServices.LoginCheckRequest inValue = new WindowsFormsApp1.CustomersServices.LoginCheckRequest();
            inValue.Body = new WindowsFormsApp1.CustomersServices.LoginCheckRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            return ((WindowsFormsApp1.CustomersServices.ConvertSoap)(this)).LoginCheckAsync(inValue);
        }
    }
}
